---
subtitle: "Analyse simple du texte"
---
::: {.panel-tabset}

# Généralités

On ne travaille que sur les mots (ou pour être exact les racines des mots) en analysant uniquement leur fréquence dans le texte.

```{r}
#| label: setup

rm(list = ls())

library("tidyverse")
library("dplyr")
library("readODS")
library("gtsummary")
library("kableExtra")
library("plotly")
library("proustr")
library("ggsci")
library("tidytext")
library("SnowballC")
library("ggwordcloud")
library("RColorBrewer")
```

```{r}
#| label: import

tt <- NULL
htdoc <- NULL
nn <- 0
prof <- c("IDE en consultation", "Assistante sociale", 
          "Cadre supérieure de santé", "Pharmacien 1",
          "Pharmacien 2", "Cadre faisant fonction",
          "Hématologue", "Secrétaire médicale")

mesmots <- as_tibble(c("c'est", "ça", "donc", "fait", "parce",
                       "peut","quand","c'et","ca","qu’il",
             "être", "puis", "aussi", "plus", "fois", "là", "sous",
             "après", "peux", "alors", "beaucoup", "comme", "quil",
             "faut", "voilà", "j'ai", "n’est", "vont","oui", "peutêtr",
             "ben", "peu", "tout", "car", "quelqu","qu'on",
             "qu'il","c’est", "qu’on","j’ai",
             "puisqu","ell","vraiment", "évidem", "non","jai", "sai",
"déjà", "qu'il", "n'y", "qu'on", "n’ai","n’y",
             "tous", "avoir","estc", "autr", "...", "quon", "ouai", "entr", "dire", "dirai" ,"commen", "voi"))


for(nt in 1:8){
nomtxt <- paste0("datas/entretien",nt,".txt")
texte <- readr::read_file(nomtxt)
profession <- prof[nt]
ll <- c(nt,profession,texte)
tt <- rbind(tt,ll)
}
stopw <- proust_stopwords()
stopw <- stopw$word

tt <- as_tibble(tt)
names(tt) <- c("id", "profession", "texte")
```



```{r}
#| label: mots

zz <- tt |> 
tidytext::unnest_tokens(output="mots",
                        input=texte,
                        token="words") |> 
  anti_join(proustr::proust_stopwords(),by=c("mots"="word")) |> 
  anti_join(as_tibble(mesmots),by=c("mots"="value")) |> 
  anti_join(get_stopwords("fr"),by=c("mots"="word")) |> 
  mutate(mots = wordStem(mots, language = "fr"))
```




```{r}
#| label: macro-tabfq
tabfq <- function(dd){
kbl(head(dd, 10)) |> 
  kable_material(c("striped", "hover"))
}
```

```{r}
#| label: macro-nuage

nuage <- function(d = docs){
zz |> 
  count(mots, sort = TRUE) |> 
  head(50) |> 
  ggplot() +
  aes(label = mots, size= n, color = n) +
  geom_text_wordcloud(grid_size = 20) +
  scale_size_area(max_size = 20) +
  scale_color_viridis_c()
}
```

```{r}
#| label: macro-figfq

figfq <- function(d = docs,nmax = 6){
  gg <- d |> 
  dplyr::filter(n > nmax) |> 
  ggplot() +
  aes(x = fct_reorder(mots,n, .desc = FALSE), y = n) +
  geom_bar(stat="identity") +
  labs(
    title = "Mots les plus fréquents - IDE en consultation",
    y = "Fréquence",
    caption = "Nombre d'occurence des mots significatifs (réduits à leur racine)  les plus fréquents.",
  ) +
  theme_light() +
  scale_color_viridis_c() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.y.right = element_blank(),
    legend.title = element_text(size = 12),
    axis.title.y = element_blank(),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "none") +
coord_flip()
  
ggplotly(gg)
}
```


# Entretiens

::: {.panel-tabset group="Entretiens"}

## IDE en consultation

```{r}
#| label: intro

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```


**`r nprof`**


```{r}
#| label: tbl-MOTS1
#| tbl-cap: "Mots les plus fréquents - IDE en consultation"

tabfq(docs)
```

```{r}
#| label: fig-nuage1
#| fig-cap: "Mots les plus fréquents - IDE en consultation"
#| fig-alt: "Mots les plus fréquents - IDE en consultation. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-MOTS1
#| fig-cap: "Mots les plus fréquents - IDE en consultation"
#| fig-alt: "Mots les plus fréquents - IDE en consultation. Les valeurs sont dans le tableau précédent"

figfq()
```

## Assistante sociale


```{r}
#| label: tbl-mots2
#| tbl-cap: "Mots les plus fréquents - Assistante sociale"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```

```{r}
#| label: fig-nuage2
#| fig-cap: "Mots les plus fréquents - Assistante sociale"
#| fig-alt: "Mots les plus fréquents - Assistante sociale. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots2
#| fig-cap: "Mots les plus fréquents - Assistante sociale"
#| fig-alt: "Mots les plus fréquents - Assistante sociale. Les valeurs sont dans le tableau précédent"

figfq(nmax = 7)
```

## Cadre supérieure de santé


```{r}
#| label: tbl-mots3
#| tbl-cap: "Mots les plus fréquents - Cadre supérieure de santé"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)

```

```{r}
#| label: fig-nuage3
#| fig-cap: "Mots les plus fréquents - Cadre supérieure de santé"
#| fig-alt: "Mots les plus fréquents - Cadre supérieure de santé. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-MOTS3
#| fig-cap: "Mots les plus fréquents - Cadre supérieure de santé"
#| fig-alt: "Mots les plus fréquents - Cadre supérieure de santé. Les valeurs sont dans le tableau précédent"

figfq(nmax = 7)
```

## Pharmacien 1


```{r}
#| label: tbl-mots4
#| tbl-cap: "Mots les plus fréquents - Pharmacien"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)

```

```{r}
#| label: fig-nuage4
#| fig-cap: "Mots les plus fréquents - Pharmacien"
#| fig-alt: "Mots les plus fréquents - Pharmacien. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots4
#| fig-cap: "Mots les plus fréquents - Pharmacien"
#| fig-alt: "Mots les plus fréquents - Pharmacien. Les valeurs sont dans le tableau précédent"

figfq(nmax = 7)
```

## Pharmacien 2

**`r prof[5]`**

```{r}
#| label: tbl-mots5
#| tbl-cap: "Mots les plus fréquents - Pharmacien"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```

```{r}
#| label: fig-nuage5
#| fig-cap: "Mots les plus fréquents - Pharmacien"
#| fig-alt: "Mots les plus fréquents - Pharmacien. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots5
#| fig-cap: "Mots les plus fréquents - Pharmacien"
#| fig-alt: "Mots les plus fréquents - Pharmacien. Les valeurs sont dans le tableau précédent"

figfq(nmax = )
```

## Cadre faisant fonction

**`r prof[6]`**

```{r}
#| label: tbl-mots6
#| tbl-cap: "Mots les plus fréquents - Cadre faisant fonction"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```

```{r}
#| label: fig-nuage6
#| fig-cap: "Mots les plus fréquents - Cadre faisant fonction"
#| fig-alt: "Mots les plus fréquents - Cadre faisant fonction. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots6
#| fig-cap: "Mots les plus fréquents - Cadre faisant fonction"
#| fig-alt: "Mots les plus fréquents - Cadre faisant fonction. Les valeurs sont dans le tableau précédent"

figfq(nmax = 7)
```

## Hématologue

**`r prof[7]`**

```{r}
#| label: tbl-mots7
#| tbl-cap: "Mots les plus fréquents - Hématologue"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```

```{r}
#| label: fig-nuage7
#| fig-cap: "Mots les plus fréquents - Hématologue"
#| fig-alt: "Mots les plus fréquents - Hématologue. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots7
#| fig-cap: "Mots les plus fréquents - Hématologue"
#| fig-alt: "Mots les plus fréquents - Hématologue. Les valeurs sont dans le tableau précédent"

figfq(nmax = 3)
```

## Secrétaire médicale

**`r prof[8]`**

```{r}
#| label: tbl-mots8
#| tbl-cap: "Mots les plus fréquents - Secrétaire médicale"

nn <- nn +1
nprof = prof[nn]
docs <- zz |> 
  dplyr::filter(profession == nprof) |> 
  dplyr::count(mots, sort = TRUE)
```

```{r}
#| label: fig-nuage8
#| fig-cap: "Mots les plus fréquents - Secrétaire médicale"
#| fig-alt: "Mots les plus fréquents - Secrétaire médicale. Les valeurs sont dans le tableau précédent"

nuage()
```

```{r}
#| label: fig-mots8
#| fig-cap: "Mots les plus fréquents - Secrétaire médicale"
#| fig-alt: "Mots les plus fréquents - Secrétaire médicale. Les valeurs sont dans le tableau précédent"

figfq(nmax = 2)
```

:::

# Comparaisons

```{r}
# Comparaisons
#| label: tbl-mots-comp
#| tbl-cap: "Mots les plus fréquents"

docs <- zz |> 
  dplyr::count(mots, sort = TRUE) |> 
  head(10) 

czz <- zz |> 
  dplyr::filter(mots %in% docs$mots) |> 
  dplyr::count(profession, mots, sort = TRUE)|> 
  mutate(across(is.character, as.factor))
```

```{r}
#| label: comp1
#| fig-cap: Mots les plus fréquents par profession

czz |> 
  ggplot() +
  aes(x = fct_reorder(mots,n, .desc = TRUE), y = n, fill = profession) +
  geom_bar(stat="identity", position = "dodge") +
  labs(
    title = "Mots les plus fréquents par profession",
    caption = "Nombre d'occurences des mots significatifs
    (réduits à leur racine) les plus fréquents."
  ) +
  theme_light() +
scale_color_viridis_c() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.y.right = element_blank(),
    legend.title = element_text(size = 12),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_blank(),
    legend.position = "none") +
    facet_grid(profession~.,
               scales = "free") 
```



:::